spring:
  # 数据源配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  # 时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 开发环境关闭缓存，以便在修改页面时实时生效
  #    cache: true # 性能压测用
  # redis
  redis:
    host: 192.168.56.10
    port: 6379
  # SpringCache
  cache:
    type: redis
    redis:
      # 过期时间设置为3600s，即1小时
      time-to-live: 3600000
      # 设置key的前缀,一般情况下不要自定统一前缀,方便分区处理
      #      key-prefix: _CACHE
      # key是否使用前缀
      use-key-prefix: true
      # 是否允许空值. 防止缓存穿透，可缓存null值
      cache-null-values: true

# Mybatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

# 日志级别调整，方便查看sql
logging:
  level:
    xyz.funnyboy.gulimall.product: debug
#    xyz.funnyboy.gulimall.product: error # 性能压测用
