pipeline {
  agent {
    node {
      label 'maven'
    }
  }

  parameters {
    string(name: 'PROJECT_VERSION', defaultValue: 'v1.0', description: '项目版本')
    string(name: 'PROJECT_NAME', defaultValue: 'gulimall-gateway', description: '构建模块')
  }

  environment {
      // REGISTRY = 'docker.io'
      // DOCKER_CREDENTIAL_ID = 'dockerhub-id'
      // DOCKERHUB_NAMESPACE = 'vectorx'
      REGISTRY = 'registry.cn-shanghai.aliyuncs.com'
      DOCKER_CREDENTIAL_ID = 'ali-dockerhub-id'
      DOCKERHUB_NAMESPACE = 'funnyboy'
      GITEE_CREDENTIAL_ID = 'gitee-id'
      KUBECONFIG_CREDENTIAL_ID = 'demo-kubeconfig'
      GITEE_ACCOUNT = 'vectorx'
      SONAR_CREDENTIAL_ID = 'sonarqube-id'
      BRANCH_NAME = 'master'
  }

  stages {
    stage('拉取代码') {
      steps {
        git(url: 'https://gitee.com/vectorx/gulimall.git', credentialsId: 'gitee-id', branch: "$BRANCH_NAME", changelog: true, poll: false)
        sh 'echo 正在构建 $PROJECT_NAME  版本号：$PROJECT_VERSION 将会提交给 $REGISTRY 镜像仓库'
      }
    }
    stage('编译安装') {
      steps {
        container ('maven') {
          sh 'mvn clean install -Dmaven.test.skip=true -Dfile.encoding=UTF-8 -gs `pwd`/mvn-settings.xml'
        }
      }
    }
    // stage('sonar代码质量分析') {
    //   steps {
    //     container ('maven') {
    //       input(id: 'sonar-code-analyze', message: '要进行sonar代码质量分析吗?')
    //       withCredentials([string(credentialsId: "$SONAR_CREDENTIAL_ID", variable: 'SONAR_TOKEN')]) {
    //         withSonarQubeEnv('sonar') {
    //          sh 'echo 当前目录 `pwd`'
    //          sh "mvn sonar:sonar -gs `pwd`/mvn-settings.xml -Dsonar.branch=$BRANCH_NAME -Dsonar.login=$SONAR_TOKEN"
    //         }
    //       }
    //       timeout(time: 1, unit: 'HOURS') {
    //         waitForQualityGate abortPipeline: false
    //       }
    //     }
    //   }
    // }
    stage ('推送最新镜像') {
      steps {
          container ('maven') {
            sh 'cd $PROJECT_NAME && docker build -f Dockerfile -t $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER .'
            withCredentials([usernamePassword(passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,credentialsId : "$DOCKER_CREDENTIAL_ID" ,)]) {
              sh 'echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
              sh 'docker tag  $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest '
              sh 'docker push  $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest '
            }
          }
      }
    }
    stage('部署到k8s') {
      steps {
        // 双引号才可以动态取值，单引号会有问题哦~
        // input(id: "deploy-to-dev-$PROJECT_NAME", message: "是否将 $PROJECT_NAME 部署到集群中?")
        kubernetesDeploy(configs: "$PROJECT_NAME/deploy/**", enableConfigSubstitution: true, kubeconfigId: "$KUBECONFIG_CREDENTIAL_ID")
      }
    }
    stage('发布版本'){
      when{
        expression{
          return params.PROJECT_VERSION =~ /v.*/
        }
      }
      steps {
        container ('maven') {
          // input(id: 'release-image-with-tag', message: '发布当前版本镜像吗?')
          sh 'docker tag  $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION '
          sh 'docker push  $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION '
          // withCredentials([usernamePassword(credentialsId: "$GITEE_CREDENTIAL_ID", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
          //   sh 'git config --global user.email "uxiahnan@outlook.com" '
          //   sh 'git config --global user.name "vectorx" '
          //   sh 'git tag -a $PROJECT_NAME-$PROJECT_VERSION -m "$PROJECT_NAME-$PROJECT_VERSION" '
          //   sh 'git push http://$GIT_USERNAME:$GIT_PASSWORD@gitee.com/$GITEE_ACCOUNT/gulimall.git --tags --ipv4'
          // }
        }
      }
    }
  }
}
