pipeline {
  agent {
    node {
      label 'maven'
    }

  }
  stages {
    stage('拉取代码') {
      steps {
        git(url: 'https://github.com/vectorxxxx/12-GrainMall.git', credentialsId: 'github-id', branch: 'main', changelog: true, poll: false)
        sh 'echo $PROJECT_VERSION'
        sh 'echo $PROJECT_NAME'
      }
    }
  }
  parameters {
    string(name: 'PROJECT_VERSION', defaultValue: 'v0.0Beta', description: '')
    string(name: 'PROJECT_NAME', defaultValue: 'v0.0Beta', description: '')
  }
}
