spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
  # redis
  redis:
    host: 192.168.56.10
    port: 6379
  # 使用 redis 存储 session
  session:
    store-type: redis

server:
  port: 20000
  # 配置session过期时间
  servlet:
    session:
      timeout:30m

# gitee 社交登录
gitee:
  oauth:
    host: https://gitee.com
    client-id: 59908830bb4e9a49f9e6850b3ad69af0b588cbbbad52401258cf52c00ea7b327
    client-secret: f49f15371efe5f917149f9b5d923443702280731c76a11f1c616d33bbbbdbcfc
    redirect-uri: http://auth.gulimall.com/oauth2.0/gitee/success
    response-type: code
    grant-type: authorization_code
    fail-path: redirect:http://auth.gulimall.com/login.html
    success-path: redirect:http://gulimall.com
