spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
  # redis
  redis:
    host: 192.168.56.10

server:
  port: 20000

