server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # redis
  redis:
    host: 192.168.56.10
    port: 6379
  # spring session
  session:
    store-type: redis


# 配置线程池
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
