spring:
  application:
    name: gulimall-search
  thymeleaf:
    cache: false # 开发期间关闭缓存
  # redis
  redis:
    host: 192.168.56.10
    port: 6379
  # 使用 redis 存储 session
  session:
    store-type: redis
  profiles:
    active: dev

server:
  # 配置session过期时间
  servlet:
    session:
      timeout: 30m

logging:
  level:
    xyz.funnyboy.gulimall.search: debug
